import type { ActivityEvent, Project, Story, Task, Workspace } from './types'
import { PROVIDERS } from './types'
import { daysAgo, daysUntil, describeDue, formatDay, toDayString } from './dates'

/**
 * The status report is the thing a PM actually owes upward, and until Phase 1
 * the workspace had no way to produce one: no completion times, no history.
 * Now it does, so this is a pure function over the data — no model call, no
 * API key, nothing to go stale.
 */

export interface ReportInput {
  project: Project
  tasks: Task[]
  stories: Story[]
  activity: ActivityEvent[]
  /** Reporting window in days. */
  days: number
}

function bullet(items: string[]): string {
  return items.length ? items.map((i) => `- ${i}`).join('\n') : '_Nothing to report._'
}

function taskLine(t: Task): string {
  const bits = [t.assignee, t.provider !== 'Human' ? `via ${t.provider}` : null].filter(Boolean)
  const suffix = bits.length ? ` (${bits.join(', ')})` : ''
  return `${t.title}${suffix}`
}

export function buildReport({ project, tasks, stories, activity, days }: ReportInput): string {
  const since = daysAgo(days)
  const done = tasks.filter((t) => t.status === 'done')
  const pct = tasks.length ? Math.round((done.length / tasks.length) * 100) : 0

  const shipped = tasks
    .filter((t) => t.status === 'done' && t.completedAt !== null && t.completedAt >= since)
    .sort((a, b) => (a.completedAt ?? 0) - (b.completedAt ?? 0))

  const inFlight = tasks.filter((t) => t.status === 'in_progress')

  const overdue = tasks
    .filter((t) => t.status !== 'done' && t.dueDate && daysUntil(t.dueDate) < 0)
    .sort((a, b) => daysUntil(a.dueDate!) - daysUntil(b.dueDate!))

  const upcoming = tasks
    .filter((t) => t.status !== 'done' && t.dueDate && daysUntil(t.dueDate) >= 0 && daysUntil(t.dueDate) <= 7)
    .sort((a, b) => daysUntil(a.dueDate!) - daysUntil(b.dueDate!))

  const unassigned = tasks.filter((t) => t.status !== 'done' && !t.assignee)

  // Attribution over what actually shipped in the window — the product's whole
  // thesis is knowing which model or human did the work.
  const mix = PROVIDERS.map((p) => ({
    provider: p,
    count: shipped.filter((t) => t.provider === p).length,
  })).filter((m) => m.count > 0)

  const storyLines = stories.map((s) => {
    const own = tasks.filter((t) => t.storyId === s.id)
    const closed = own.filter((t) => t.status === 'done').length
    return `${s.title} — ${closed}/${own.length} (${s.priority})`
  })

  const changes = activity.filter((e) => e.createdAt >= since).length

  const header = [
    `# ${project.name} — status report`,
    '',
    `_${formatDay(toDayString(new Date()))} · last ${days} days_`,
    '',
    `**${pct}% complete** — ${done.length} of ${tasks.length} tasks done.`,
    project.targetDate
      ? `**Target ${formatDay(project.targetDate)}** — ${describeDue(project.targetDate)}.`
      : '_No target date set._',
    overdue.length ? `**${overdue.length} overdue.**` : '',
    '',
  ]
    .filter((line) => line !== '')
    .join('\n')

  const sections = [
    ['## Shipped', bullet(shipped.map(taskLine))],
    ['## In progress', bullet(inFlight.map(taskLine))],
    [
      '## Overdue',
      bullet(overdue.map((t) => `${taskLine(t)} — due ${formatDay(t.dueDate!)}, ${describeDue(t.dueDate!)}`)),
    ],
    [
      '## Due in the next 7 days',
      bullet(upcoming.map((t) => `${taskLine(t)} — ${formatDay(t.dueDate!)}`)),
    ],
    ['## Stories', bullet(storyLines)],
    [
      '## Who shipped it',
      mix.length
        ? bullet(mix.map((m) => `${m.provider}: ${m.count}`))
        : '_Nothing completed in this window._',
    ],
  ]

  const risks: string[] = []
  if (overdue.length) risks.push(`${overdue.length} task(s) past their due date.`)
  if (unassigned.length) risks.push(`${unassigned.length} open task(s) have no owner.`)
  if (project.targetDate && daysUntil(project.targetDate) < 0) {
    risks.push(`The project target (${formatDay(project.targetDate)}) has passed.`)
  }
  if (!shipped.length && tasks.length) risks.push(`Nothing was completed in the last ${days} days.`)
  sections.push(['## Risks', bullet(risks)])

  const footer = `\n---\n_${changes} recorded change${changes === 1 ? '' : 's'} in this window. Generated by Cairn._\n`

  return `${header}\n${sections.map(([h, body]) => `${h}\n\n${body}`).join('\n\n')}\n${footer}`
}

/** Everything the report needs for one project, pulled out of the workspace. */
export function reportInput(ws: Workspace, projectId: string, days: number): ReportInput | null {
  const project = ws.projects.find((p) => p.id === projectId)
  if (!project) return null
  return {
    project,
    tasks: ws.tasks.filter((t) => t.projectId === projectId),
    stories: ws.stories.filter((s) => s.projectId === projectId),
    activity: ws.activity.filter((e) => e.projectId === projectId),
    days,
  }
}
